version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - payment-service
      - stock-service

  order-service:
    container_name: order-service
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    depends_on:
      rmq:
        condition: service_healthy
    links:
      - rmq

  order-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    container_name: stock-service
    build: ./stock
    image: stock:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    depends_on:
      rmq:
        condition: service_healthy
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    container_name: payment-service
    build: ./payment
    image: user:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    depends_on:
      rmq:
        condition: service_healthy
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  payment-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  rmq:
    container_name: rmq
    image: 'rabbitmq:3.10-management'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics check_port_listener 5672"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service-test:
    container_name: order-service-test
    build: ./order-service
    env_file:
      - env/order_redis.env
    depends_on:
      rmq:
        condition: service_healthy
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-test:
    container_name: payment-service-test
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    depends_on:
      rmq:
        condition: service_healthy
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-test:
    container_name: stock-service-test
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    depends_on:
      rmq:
        condition: service_healthy
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq
