version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-proxy
      - payment-proxy
      - stock-proxy

  order-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  rmq:
    container_name: rmq
    image: 'rabbitmq:3.10-management'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmq-diagnostics check_port_listener 5672"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    container_name: order-service
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service:
    container_name: payment-service
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service:
    container_name: stock-service
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-2:
    container_name: order-service-2
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-2:
    container_name: payment-service-2
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-2:
    container_name: stock-service-2
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-3:
    container_name: order-service-3
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-3:
    container_name: payment-service-3
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-3:
    container_name: stock-service-3
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-4:
    container_name: order-service-4
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-4:
    container_name: payment-service-4
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-4:
    container_name: stock-service-4
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq
  order-service-5:
    container_name: order-service-5
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-5:
    container_name: payment-service-5
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-5:
    container_name: stock-service-5
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-6:
    container_name: order-service-6
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-6:
    container_name: payment-service-6
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-6:
    container_name: stock-service-6
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-7:
    container_name: order-service-7
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-7:
    container_name: payment-service-7
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-7:
    container_name: stock-service-7
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq
  order-service-8:
    container_name: order-service-8
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-8:
    container_name: payment-service-8
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-8:
    container_name: stock-service-8
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-9:
    container_name: order-service-9
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-9:
    container_name: payment-service-9
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-9:
    container_name: stock-service-9
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-service-10:
    container_name: order-service-10
    build: ./order-service
    env_file:
      - env/order_redis.env
    links:
      - rmq
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq

  payment-service-10:
    container_name: payment-service-10
    build: ./payment-service
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  stock-service-10:
    container_name: stock-service-10
    build: ./stock-service
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  payment-proxy:
    container_name: payment-proxy
    build: ./payment
    image: payment-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-proxy:
    container_name: order-proxy
    build: ./order
    image: order-proxy:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    links:
      - rmq

  stock-proxy:
    container_name: stock-proxy
    build: ./stock
    image: stock-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  payment-proxy-2:
    container_name: payment-proxy-2
    build: ./payment
    image: payment-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-proxy-2:
    container_name: order-proxy-2
    build: ./order
    image: order-proxy:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    links:
      - rmq

  stock-proxy-2:
    container_name: stock-proxy-2
    build: ./stock
    image: stock-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  payment-proxy-3:
    container_name: payment-proxy-3
    build: ./payment
    image: payment-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-proxy-3:
    container_name: order-proxy-3
    build: ./order
    image: order-proxy:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    links:
      - rmq

  stock-proxy-3:
    container_name: stock-proxy-3
    build: ./stock
    image: stock-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  payment-proxy-4:
    container_name: payment-proxy-4
    build: ./payment
    image: payment-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-proxy-4:
    container_name: order-proxy-4
    build: ./order
    image: order-proxy:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    links:
      - rmq

  stock-proxy-4:
    container_name: stock-proxy-4
    build: ./stock
    image: stock-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq
  payment-proxy-5:
    container_name: payment-proxy-5
    build: ./payment
    image: payment-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-proxy-5:
    container_name: order-proxy-5
    build: ./order
    image: order-proxy:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    links:
      - rmq

  stock-proxy-5:
    container_name: stock-proxy-5
    build: ./stock
    image: stock-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq
  payment-proxy-6:
    container_name: payment-proxy-6
    build: ./payment
    image: payment-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/payment_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq

  order-proxy-6:
    container_name: order-proxy-6
    build: ./order
    image: order-proxy:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - PAYMENT_SERVICE=http://gateway:80/payment
      - STOCK_SERVICE=http://gateway:80/stock
      - RMQ_HOST=rmq
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/order_redis.env
    links:
      - rmq

  stock-proxy-6:
    container_name: stock-proxy-6
    build: ./stock
    image: stock-proxy:latest
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    env_file:
      - env/stock_redis.env
    links:
      - rmq
    environment:
      - RMQ_HOST=rmq
