apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rmq
  name: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: rmq
    spec:
      containers:
        - image: rabbitmq:3.10-management
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics check_port_listener 5672
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: rmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources: {}
      restartPolicy: Always
status: {}
