apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-db
  name: stock-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: stock-db
    spec:
      containers:
        - args:
            - redis-server
            - --requirepass
            - redis
            - --maxmemory
            - 512mb
          image: redis:latest
          name: stock-db
          resources: {}
      restartPolicy: Always
status: {}
